on:
  push:
    branches:
      - pruebas_actions
  pull_request:

name: CI
jobs:
  
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cambiar directorio
      run: cd laradock
      
    - name: Run container
      working-directory: /home/runner/work/evidentia/evidentia/
      run: |
        chmod +x install_laradock.sh
        sh install_laradock.sh
        cd laradock
        docker-compose up -d nginx mysql phpmyadmin redis workspace    
    - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      with:
        timeout: 1h
        port: 80
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
  
