on:
  push:
    branches:
      - pruebas_actions
  pull_request:

name: CI
jobs:
  
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest

    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cambiar directorio
      run: cd laradock
      
    - name: Run container
      working-directory: ./laradock
      run: |
        echo "$GITHUB.REPOSITORY"
        find src
        docker-compose -f "laradock/docker-compose.yml" up -d --build
    
    - uses: apogiatzis/ngrok-tunneling-action@v0.1.4
      with:
        timeout: 1h
        port: 80
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
  
