on:
  push:
    branches:
      - pruebas_actions
  pull_request:

name: CI
jobs:
  
  deploy:
    name: Deploy challenge
    runs-on: ubuntu-latest
    
    steps:
    
 
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Cambiar directorio
      run: cd laradock
      
    - name: Run container
      working-directory: /home/runner/work/evidentia/evidentia/
      run: |
        chmod +x install_laradock.sh
        sh install_laradock.sh
        cd laradock
        docker-compose up -d nginx mysql phpmyadmin redis workspace    
        docker exec -it laradock_php-fpm bash
        chown -R www-data:www-data /var/www/storage
    - uses: serrojjim/ngrok-tunneling-action@v0.1.6
      with:
        port: 80
        ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
  
