on:
  push:
    branches: 
      - pruebas_actions
  pull_request:

name: CI
jobs:
  
  install:
    name: Instalación
    runs-on: ubuntu-latest
    
    steps:
    
 
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
        
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Instalando laradock y lanzando container
      working-directory: /home/runner/work/evidentia/evidentia/
      run: |
        chmod +x install_laradock.sh
        sh install_laradock.sh
        cd laradock
        docker-compose up -d nginx mysql phpmyadmin redis workspace   
        
  
        
  container:
    runs-on: ubuntu-latest
    container: laradock_php-fpm
    
    steps:
      - name: Dando permisos      
        run: |
          chown -R www-data:www-data /var/www

  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Lanzando en ngrok 
        uses: serrojjim/ngrok-tunneling-action@v0.1.6
        with:
          port: 80
          ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
   
  
