on:
  push:
    branches:
      - develop

name: CI
jobs:
  phpunit:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: evidentia
          MYSQL_USER: evidentia
          MYSQL_PASSWORD: secret
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
         access_token: ${{ github.token }}
         
      - name: Verify MySQL connection from host
        run: |
          mysql --host 127.0.0.1 --port 33306 -uroot -psecret -e "GRANT ALL ON *.*  TO 'evidentia'@'%' identified by 'secret'; FLUSH PRIVILEGES;"
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install composer dependencies
        run: |
          rm composer.lock
          composer install --no-scripts
          composer update
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan migrate
          php artisan db:seed
          php artisan db:seed --class=InstancesTableSeeder
      - name: Run Testsuite
        run: vendor/bin/phpunit tests/

  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Lanzando  
      uses: satak/webrequest-action@master
      with:
       url: http://evidentia-generador-diplomas.eu.ngrok.io/deploy?username=evidentia&password=secret
       method: GET
       
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
        with:
          tool: <CLIENT_SIDE_TOOL_NAME>
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          upload: true
          max-allowed-issues: 2147483647
     
      
    
      
